// AUTO_GENERATED BY MVP Java Maven Plugin
package com.javafx.graaljs.view.autogen;

public enum SceneEnum {

  MAIN {
    @Override
    public String getFxmlFile() {
      return "/fxml/Main.fxml";
    }

    @Override
    public String getTitle() {
      return getStringFromResourceBundle("main.title");
    }
  };

  public abstract String getFxmlFile();

  public abstract String getTitle();

  public String getStringFromResourceBundle(String key) {
    return java.util.ResourceBundle.getBundle("Bundle").getString(key);
  }
}
